feat: configurable journey planner api configurations
AtB-AS/planner-web pull request #208
Opened 2024-01-18 09:25 UTC by mortennordseth

Because the journey planner API configurations differ for AtB, NFK, and FRAM we need to have them configurable. This makes that possible by setting environment variables. 

Closes https://github.com/AtB-AS/kundevendt/issues/16416

2024-01-18 09:38 UTC, adriansberg commented
How is this configured for the app? In the bff?

2024-01-19 07:49 UTC, mikaelbr requested changes
I think this should be part of org data instead. It isn't needed as a secret but just easily accessible information

2024-01-19 09:58 UTC, mortennordseth commented
I've moved the configuration to the org data and updated the values to match what is used in the app. 

> How is this configured for the app? In the bff?

This is configured in the app. Some are editable with preferences

2024-01-23 13:50 UTC, adriansberg commented on orgs/schema-validation.json
> +        "journeyAPIConfigurations": {
```suggestion
        "journeyApiConfigurations": {
```

2024-01-23 13:52 UTC, adriansberg commented on orgs/schema-validation.json
> +            "WAIT_RELUCTANCE": {
Do these need to be capitalised when they're not defined as constants, but as properties in an object?

2024-01-23 13:53 UTC, adriansberg approved these changes
Looks good, other than some nitpicky comments.

2024-01-24 09:13 UTC, merged