chore: update translations
AtB-AS/planner-web pull request #419
Opened 2024-11-05 14:00 UTC by jonasbrunvoll

Draft

2024-11-12 08:48 UTC, mortennordseth commented on src/translations/pages/contact.ts
> +              "Hvis du vil ha hjelp med en billett du allrede har kjøpt, trenger vi å vite ordre-id. Den finner du på billetten i appen, eller på kvitteringen din. Du finner ordre-id også på utgåtte
```suggestion
              "Hvis du vil ha hjelp med en billett du allerede har kjøpt, trenger vi å vite ordre-id. Den finner du på billetten i appen, eller på kvitteringen din. Du finner ordre-id også på utgåtte billetter. Gjelder forespørslen din flere billetter, må du huske å sende med ordre-id for alle billettene. Ved flere ordre-id-er, skill med komma (',').",
```

2024-11-12 11:52 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Please enter your firstname',
```suggestion
          'Please enter your first name',
```

2024-11-12 11:53 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Please enter your lastname',
```suggestion
          'Please enter your last name',
```

"Surname" eller "family name" er og alternativer. Hva er brukt tidligere, i app/nettbutikk feks?

2024-11-12 11:54 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Vennligst fyll ut e-post adressen din',
```suggestion
          'Vennligst fyll ut e-postadressen din',
```

2024-11-12 11:54 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Vennligst fyll ut e-post adressa di',
```suggestion
          'Vennligst fyll ut e-postadressa di',
```

2024-11-12 11:55 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Vennligst fyll ut bostedsadressa di',
Skulle det vært bustad? https://ordbokene.no/nob/bm,nn/bostedsadresse%7Cbustadadresse

2024-11-12 11:55 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Vennligst fyll ut bostaden di',
```suggestion
          'Vennligst fyll ut bustaden di',
```

2024-11-12 11:56 UTC, adriansberg requested changes
Lagt inn kommentarer/forslag

2024-11-12 12:18 UTC, jonasbrunvoll commented on src/translations/pages/contact.ts
> +          'Vennligst fyll ut bostedsadressa di',
Stemmer. Jeg fant ikke bustadsdresse som et lovlig alternativ når jeg søkte det opp, men det ser ut som jeg har blinkset.

2024-11-12 14:50 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Vennligst fyll ut ditt telefonummer',
```suggestion
          'Vennligst fyll ut ditt telefonnummer',
```

2024-11-12 14:50 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Vennligst fyll ut ditt telefonummer',
```suggestion
          'Vennligst fyll ut ditt telefonnummer',
```

2024-11-12 14:52 UTC, adriansberg commented on src/translations/pages/contact.ts
> +          'Vennligst fyll ut bustedsadressa di',
```suggestion
          'Vennligst fyll ut bustadadressa di',
```

2024-11-12 14:53 UTC, adriansberg requested changes
Some more typos

2024-11-13 08:19 UTC, adriansberg approved these changes

2024-11-13 08:24 UTC, merged